[package]
name = "easy-rar-to-cbz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unrar = "0.4.4"
tempfile = "3.3.0"
zip = "0.6.4"
zip-extensions = "0.6.1"